//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are any validation errors.
        /// </summary>
        internal static string messageBadRequestDetail {
            get {
                return ResourceManager.GetString("messageBadRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione! Impossibile eliminare l&apos;elemento in quanto in uso in altre gestioni..
        /// </summary>
        internal static string messageCannotDelete {
            get {
                return ResourceManager.GetString("messageCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row not found on db.
        /// </summary>
        internal static string messageDbRowNotFound {
            get {
                return ResourceManager.GetString("messageDbRowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error on db.
        /// </summary>
        internal static string messageDbUpdate {
            get {
                return ResourceManager.GetString("messageDbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminare l&apos;elemento selezionato ?.
        /// </summary>
        internal static string messageDeletingItem {
            get {
                return ResourceManager.GetString("messageDeletingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic error.
        /// </summary>
        internal static string messageGenericError {
            get {
                return ResourceManager.GetString("messageGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;elemento è già presente!.
        /// </summary>
        internal static string messageItemAlreadyExists {
            get {
                return ResourceManager.GetString("messageItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username / Password!.
        /// </summary>
        internal static string messageLogonFailed {
            get {
                return ResourceManager.GetString("messageLogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lunghezza massima è {0}!.
        /// </summary>
        internal static string messageMaxLength {
            get {
                return ResourceManager.GetString("messageMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il valore deve essere compreso nel range [{1}, {2}].
        /// </summary>
        internal static string messageRange {
            get {
                return ResourceManager.GetString("messageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is mandatory!.
        /// </summary>
        internal static string messageRequired {
            get {
                return ResourceManager.GetString("messageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La selezione è obbligatoria!.
        /// </summary>
        internal static string messageRequiredSelection {
            get {
                return ResourceManager.GetString("messageRequiredSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        internal static string messageUnauthorizedAccess {
            get {
                return ResourceManager.GetString("messageUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tipo deve essere I oppure U!.
        /// </summary>
        internal static string messageUseType {
            get {
                return ResourceManager.GetString("messageUseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il formato è errato!.
        /// </summary>
        internal static string messageWrongFormat {
            get {
                return ResourceManager.GetString("messageWrongFormat", resourceCulture);
            }
        }
    }
}
